python-binding/code-execution/src:
  - py

python-binding/code-execution/config:
  - yml
  - yaml

python-binding:
  - py
  - yml
  - yaml
  - cfg
  - xml

scenes:
  - tscn
  - scn

script-templates:
  - gd
  - uid

scripts:
  - gd
  - uid
