name: Branch format checker
on: [pull_request]
jobs:
  Branch-Format-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch files
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.2"

      - name: Install dependencies
        run: pip install pyyaml

      - name: CHANGELOG.md check
        run: test -f CHANGELOG.md

      - name: Check project structure
        run: python3 .github/workflow-script/project_structure_check.py
